# Generated by Django 3.1.2 on 2020-11-28 18:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrado',
            fields=[
                ('idAdmin', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('nombreAdmin', models.CharField(max_length=200, verbose_name='Nombre del admin')),
                ('apellidoAdmin', models.CharField(blank=True, max_length=200, verbose_name='Apellido del admin')),
                ('passwordAdmin', models.CharField(blank=True, max_length=200, verbose_name='Contraseña del admin')),
            ],
        ),
        migrations.CreateModel(
            name='jugete',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('nombreJugete', models.CharField(max_length=200)),
                ('precio', models.IntegerField(null=True)),
                ('stock', models.IntegerField(null=True)),
                ('marca', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreUsuario', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nomres')),
                ('apellidoUsuario', models.CharField(blank=True, max_length=200, null=True, verbose_name='Apellido de usuario')),
                ('mailUsuario', models.CharField(max_length=200, unique=True, verbose_name='Mail del Usuario')),
                ('usuario_activo', models.BooleanField(default=True)),
                ('usuario_administrador', models.BooleanField(default=True)),
            ],
        ),
    ]
